/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import domain.Seat;
import javax.swing.ButtonModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author han
 */
public class booking extends javax.swing.JFrame {

    /**
     * Creates new form booking
     */
    public booking(String memID,String scheID) {
        initComponents();
        tf_memID.setText(memID);
        tf_scheID.setText(scheID);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        normal = new javax.swing.JRadioButton();
        vip = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        seatno = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_memID = new javax.swing.JTextField();
        tf_scheID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        normals = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        vips = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        totalp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Booking");
        setMinimumSize(new java.awt.Dimension(540, 320));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Booking");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 13, 94, 28);

        jLabel2.setText("Type of Seat: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 140, 82, 16);

        buttonGroup1.add(normal);
        normal.setText("Normal");
        normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalActionPerformed(evt);
            }
        });
        getContentPane().add(normal);
        normal.setBounds(102, 136, 69, 25);

        buttonGroup1.add(vip);
        vip.setText("VIP");
        vip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vipActionPerformed(evt);
            }
        });
        getContentPane().add(vip);
        vip.setBounds(175, 136, 47, 25);

        jLabel3.setText("Number of Seat to book:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(12, 171, 141, 16);

        seatno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatnoActionPerformed(evt);
            }
        });
        getContentPane().add(seatno);
        seatno.setBounds(165, 168, 70, 30);

        jLabel4.setText("Member ID :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 99, 72, 16);

        jLabel5.setText("Scheduler ID:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(12, 62, 78, 16);

        tf_memID.setEditable(false);
        getContentPane().add(tf_memID);
        tf_memID.setBounds(104, 96, 62, 30);

        tf_scheID.setEditable(false);
        tf_scheID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_scheIDActionPerformed(evt);
            }
        });
        getContentPane().add(tf_scheID);
        tf_scheID.setBounds(102, 59, 62, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel6.setText("Price of Seat");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(321, 22, 74, 17);

        jLabel7.setText("Normal Seat : RM");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(241, 62, 102, 16);

        normals.setEditable(false);
        normals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalsActionPerformed(evt);
            }
        });
        getContentPane().add(normals);
        normals.setBounds(348, 59, 64, 30);

        jLabel8.setText("VIP Seat : RM");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(263, 99, 80, 16);

        vips.setEditable(false);
        getContentPane().add(vips);
        vips.setBounds(348, 96, 64, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Arrow-Back-icon (1).png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 240, 80, 25);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blue-ok-icon (1).png"))); // NOI18N
        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(120, 240, 97, 25);

        jButton3.setText("Show Price");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(320, 140, 97, 25);

        jLabel9.setText("Total Price: RM");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 210, 88, 16);

        totalp.setEditable(false);
        totalp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalpActionPerformed(evt);
            }
        });
        getContentPane().add(totalp);
        totalp.setBounds(170, 200, 64, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/q0YWfFw.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 520, 290);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void normalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_normalsActionPerformed

    private void normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalActionPerformed
        String scheID = tf_scheID.getText();
        
        try{
            SeatTier st = new SeatTier();
            Seat s = new Seat();
            s.setScheID(scheID);
            s = st.seatprice(s);
                if (s == null){
                    JOptionPane.showMessageDialog(this, "Cannot found seat details.");
                } else {
                    DefaultComboBoxModel model2 = (DefaultComboBoxModel)seatno.getModel();
                    model2.removeAllElements();
                    int count = s.getNormal();
                    for(int a=1;a<=count;a++)
                        model2.addElement(a);
                }
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        
        
    }//GEN-LAST:event_normalActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String scheID = tf_scheID.getText();
        
        try{
            SeatTier st = new SeatTier();
            Seat s = new Seat();
            s.setScheID(scheID);
            s = st.seatprice(s);
                if (s == null){
                    JOptionPane.showMessageDialog(this, "Cannot found price.");
                } else {
                    normals.setText(s.getPriceN()+"");
                    vips.setText(s.getPriceVip()+"");                    
                }
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void vipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vipActionPerformed
        String scheID = tf_scheID.getText();
        
        try{
            SeatTier st = new SeatTier();
            Seat s = new Seat();
            s.setScheID(scheID);
            s = st.seatprice(s);
                if (s == null){
                    JOptionPane.showMessageDialog(this, "Cannot found seat details.");
                } else {
                    DefaultComboBoxModel model2 = (DefaultComboBoxModel)seatno.getModel();
                    model2.removeAllElements();
                    int count = s.getVip();
                    for(int a=1;a<=count;a++)
                        model2.addElement(a);
                }
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
    }//GEN-LAST:event_vipActionPerformed

    private void seatnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatnoActionPerformed
        String scheID = tf_scheID.getText();
        
        try{
            SeatTier st = new SeatTier();
            Seat s = new Seat();
            s.setScheID(scheID);
            s = st.seatprice(s);
                if (s == null){
                    JOptionPane.showMessageDialog(this, "Cannot found seat details.");
                } else {
                    int num = (int)seatno.getSelectedItem();
                    double totalprice;
                    if(normal.isSelected())
                        totalprice = s.getPriceN()*num;
                    else
                        totalprice = s.getPriceVip()*num;
                    totalp.setText(totalprice+"");
                }
                
            } catch (Exception ex) {
            }

    }//GEN-LAST:event_seatnoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String memId = tf_memID.getText();
        dispose();
        showSche ss = new showSche(memId);
        ss.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      String memID = tf_memID.getText();
        String scheID = tf_scheID.getText();
        String seatType ;
       
        if(normal.isSelected())
            seatType = "Normal";
        else
            seatType = "VIP";
        
        int seatBook = seatno.getSelectedIndex()+1;
        double price = Double.parseDouble(totalp.getText());
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tf_scheIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_scheIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_scheIDActionPerformed

    private void totalpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton normal;
    private javax.swing.JTextField normals;
    private javax.swing.JComboBox<String> seatno;
    private javax.swing.JTextField tf_memID;
    private javax.swing.JTextField tf_scheID;
    private javax.swing.JTextField totalp;
    private javax.swing.JRadioButton vip;
    private javax.swing.JTextField vips;
    // End of variables declaration//GEN-END:variables
}
