
package UI;

import domain.Payment;
import domain.Refund;
import javax.swing.JOptionPane;

public class cancel extends javax.swing.JFrame {

    public cancel(String payID,String memID) {
        initComponents();
        tf_payID.setText(payID);
        tf_memID.setText(memID);
        try{
            payTier pt = new payTier();
            Payment p = new Payment();
            p.setPayID(payID);
            p = pt.retrievebyID(p);
                if (p == null){
                    JOptionPane.showMessageDialog(this, "Cannot found Payment details.");
                } else {
                    tf_bookID.setText(p.getBookID());
                    tf_scheID.setText(p.getScheID());
                    tf_stype.setText(p.getSeatType());
                    tf_sbook.setText(p.getSeatBook()+"");
                    tf_price.setText(p.getPrice()+"");
                    tf_refund.setText((p.getPrice()/2)+"");
                }
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_payID = new javax.swing.JTextField();
        tf_memID = new javax.swing.JTextField();
        tf_bookID = new javax.swing.JTextField();
        tf_scheID = new javax.swing.JTextField();
        tf_price = new javax.swing.JTextField();
        tf_stype = new javax.swing.JTextField();
        tf_sbook = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tf_refund = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cancellation Details");
        setMinimumSize(new java.awt.Dimension(460, 330));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Cancellation Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(41, 7, 207, 28);

        jLabel2.setText("Payment ID :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 66, 74, 16);

        jLabel3.setText("Member ID :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(183, 66, 72, 16);

        jLabel4.setText("Booking ID :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(12, 101, 69, 16);

        jLabel5.setText("Total Price :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(12, 176, 70, 16);

        jLabel6.setText("Seat Type :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(12, 141, 67, 16);

        jLabel7.setText("Seat Booked :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(178, 141, 80, 16);

        jLabel8.setText("Schedule ID :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(181, 101, 77, 16);

        tf_payID.setEditable(false);
        getContentPane().add(tf_payID);
        tf_payID.setBounds(91, 63, 74, 22);

        tf_memID.setEditable(false);
        getContentPane().add(tf_memID);
        tf_memID.setBounds(260, 63, 71, 22);

        tf_bookID.setEditable(false);
        getContentPane().add(tf_bookID);
        tf_bookID.setBounds(92, 98, 73, 22);

        tf_scheID.setEditable(false);
        getContentPane().add(tf_scheID);
        tf_scheID.setBounds(263, 98, 71, 22);

        tf_price.setEditable(false);
        getContentPane().add(tf_price);
        tf_price.setBounds(94, 173, 74, 22);

        tf_stype.setEditable(false);
        getContentPane().add(tf_stype);
        tf_stype.setBounds(91, 138, 75, 22);

        tf_sbook.setEditable(false);
        getContentPane().add(tf_sbook);
        tf_sbook.setBounds(263, 138, 71, 22);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Arrow-Back-icon (1).png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 240, 115, 25);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Close-icon.png"))); // NOI18N
        jButton2.setText("Confirm Cancellation");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 240, 200, 25);

        jLabel9.setText("Total Refund :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(176, 176, 82, 16);

        tf_refund.setEditable(false);
        getContentPane().add(tf_refund);
        tf_refund.setBounds(263, 173, 71, 22);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/q0YWfFw.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 460, 310);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      String payID = tf_payID.getText();
        String bookID = tf_bookID.getText();
        String price = tf_price.getText();
        String scheID = tf_scheID.getText();
        int seatBook = Integer.parseInt(tf_sbook.getText());
        String seatType = tf_stype.getText();
        String memID = tf_memID.getText();
        double rprice = (Double.parseDouble(price))/2;
        
        try{
            refundTier rt = new refundTier();
            String refundID = rt.storeRefund(payID,memID,rprice);
                if (refundID==null){
                    JOptionPane.showMessageDialog(this, "Cannot found Payment details.");
                } else {
                    bookTier bt = new bookTier();
                    boolean success2 = bt.deleteBook(bookID);
                    if(!success2)
                        JOptionPane.showMessageDialog(this, "Fail to cancel booking");
                    else{
                        SeatTier st = new SeatTier();
                        boolean success3 = st.addSeat(scheID,seatType,seatBook);
                        if(!success3)
                            JOptionPane.showMessageDialog(this, "Fail to add seat availability.");
                        else{
                            payTier pt = new payTier();
                            boolean success4 = pt.cancelPay(refundID,payID);
                            if(!success4)
                                JOptionPane.showMessageDialog(this, "Fail to update payment.");
                            else{
                            JOptionPane.showMessageDialog(this, "Cancel Success !!\nRefund can be claim from our center.");
                            dispose();
                            refund r = new refund(memID);
                            r.setVisible(true);
                            }
                        }
                    }
                }
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String memId = tf_memID.getText();
        
        dispose();
        refund r = new refund(memId);
        r.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new cancel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tf_bookID;
    private javax.swing.JTextField tf_memID;
    private javax.swing.JTextField tf_payID;
    private javax.swing.JTextField tf_price;
    private javax.swing.JTextField tf_refund;
    private javax.swing.JTextField tf_sbook;
    private javax.swing.JTextField tf_scheID;
    private javax.swing.JTextField tf_stype;
    // End of variables declaration//GEN-END:variables
}
