/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tsang
 */
public class CreateDriver extends javax.swing.JFrame {

    /**
     * Creates new form CreateDriver
     */
    public CreateDriver() {
        initComponents();
        this.setLocationRelativeTo(null);
        try{
            busTier bt = new busTier();
            ArrayList busID = bt.getBusList();
            DefaultComboBoxModel model = (DefaultComboBoxModel)cb_busID.getModel();
            for(int i=0; i<busID.size();i++){
                String busId = (String) busID.get(i);
                model.addElement(busId);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Fail to retrieve Bus ID");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_salary = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tf_hp = new javax.swing.JTextField();
        tf_name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_birth = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf_address = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cb_busID = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Driver");
        setMinimumSize(new java.awt.Dimension(380, 430));
        getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Create Driver");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(75, 13, 144, 28);

        jLabel6.setText("Salary : RM");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 149, 67, 16);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setText("Example : 016228776");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(215, 94, 92, 13);

        tf_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_salaryActionPerformed(evt);
            }
        });
        getContentPane().add(tf_salary);
        tf_salary.setBounds(100, 140, 70, 30);

        jLabel1.setText("Name :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(46, 62, 42, 16);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("Example : 1996-03-21");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(215, 123, 95, 13);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blue-ok-icon (1).png"))); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 330, 100, 25);

        tf_hp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_hpActionPerformed(evt);
            }
        });
        getContentPane().add(tf_hp);
        tf_hp.setBounds(100, 80, 112, 30);

        tf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nameActionPerformed(evt);
            }
        });
        getContentPane().add(tf_name);
        tf_name.setBounds(93, 51, 168, 30);

        jLabel7.setText("Handphone :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 90, 73, 16);

        jLabel5.setText("Address :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(29, 175, 55, 16);
        getContentPane().add(tf_birth);
        tf_birth.setBounds(100, 110, 115, 30);

        tf_address.setColumns(20);
        tf_address.setRows(5);
        jScrollPane1.setViewportView(tf_address);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(96, 175, 166, 96);

        jLabel3.setText("Brithday :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(28, 120, 55, 16);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Close-icon.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(140, 330, 100, 25);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Arrow-Back-icon (1).png"))); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(250, 330, 90, 25);

        jLabel9.setText("Bus In Charge :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(12, 285, 89, 16);

        cb_busID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_busIDActionPerformed(evt);
            }
        });
        getContentPane().add(cb_busID);
        cb_busID.setBounds(113, 274, 80, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/q0YWfFw.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 370, 420);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_salaryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name=tf_name.getText();
        String address=tf_address.getText();
        boolean valid = true;
        String invalid = "";
        
        //Birthday validation
        String birth=tf_birth.getText();
        int day;
        int month;
        if (birth.matches("([0-9]{4})-([0-9]{2})-([0-9]{2})"))
            valid=true;
        else{
            valid=false;
            invalid="Invalid Birthday Date format";
        }
        if(valid){
            day = Integer.parseInt(birth.substring(8));
            month = Integer.parseInt(birth.substring(5,7));
            if(day>31){
                valid=false;
                invalid = "Invalid Date";
            }
            if(month>12){
                valid=false;
                invalid = "Invalid Month";
            }
            
        }
        
        try{
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date dd = sdf.parse(birth);
        Calendar cal = Calendar.getInstance();
        String today = sdf.format(cal.getTime());
        Date tod = sdf.parse(today);
        
        if(dd.after(tod))
            valid=false;
            invalid="Birthday Cannot be furture date";
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Fail to compare Date");
        }
        
        //Salary validation
        String salaryy=tf_salary.getText();
        for(int i=0;i<salaryy.length();i++){
            char temp = salaryy.charAt(i);
            if(Character.isLetter(temp)==true){
                valid = false;
                invalid = "Please insert number only for salary";
            }
        }        
        
        //Handphone validation
        String handphone=tf_hp.getText();
        if(handphone.length()!=10){
            valid = false;
            invalid = "Handphone number should have 10 number";
        }
        for(int a=0;a<handphone.length();a++){
            char temp1 = handphone.charAt(a);
            if(Character.isLetter(temp1)==true){
                valid = false;
                invalid = "Please insert proper handphone number";
            }
        }
        
        
        String busID = (String) cb_busID.getSelectedItem();
        if(valid){
        try{
            double salary = Double.parseDouble(salaryy);
            driverTier dt = new driverTier();
            String newID=dt.createDriver(name,handphone,address,birth,salary,busID);
            if (newID == null){
                JOptionPane.showMessageDialog(this, "Error inserting new staff");
            } else {
                JOptionPane.showMessageDialog(this, "New Driver ID:"+newID+" had added.");
                dispose();
                staffSelect ss = new staffSelect();
                ss.setVisible(true);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        }else
            JOptionPane.showMessageDialog(this,invalid);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tf_name.setText("");
        tf_birth.setText("");
        tf_hp.setText("");
        tf_address.setText("");
        tf_salary.setText("");
        cb_busID.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        DriverSelection ds= new DriverSelection();
        ds.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tf_hpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_hpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_hpActionPerformed

    private void cb_busIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_busIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_busIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateDriver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateDriver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_busID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tf_address;
    private javax.swing.JTextField tf_birth;
    private javax.swing.JTextField tf_hp;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_salary;
    // End of variables declaration//GEN-END:variables
}
