/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import domain.Bus;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author han
 */
public class deleteBus extends javax.swing.JFrame {

    /**
     * Creates new form deleteBus
     */
    public deleteBus() {
        initComponents();
        try{
            busTier bt = new busTier();
            ArrayList busID = bt.getBusList();
            DefaultComboBoxModel model = (DefaultComboBoxModel)cb_busID.getModel();
            for(int i=0; i<busID.size();i++){
                String busId = (String) busID.get(i);
                model.addElement(busId);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Fail to retrieve Bus ID");
        }
        
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_busID = new javax.swing.JComboBox<String>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tf_busName = new javax.swing.JTextField();
        tf_normal = new javax.swing.JTextField();
        tf_vip = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/q0YWfFw.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delete Bus");
        setMinimumSize(new java.awt.Dimension(400, 330));
        setPreferredSize(new java.awt.Dimension(293, 245));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Delete Bus");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 40, 109, 28);

        jLabel2.setText("Bus ID :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 90, 60, 16);

        cb_busID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_busIDActionPerformed(evt);
            }
        });
        getContentPane().add(cb_busID);
        cb_busID.setBounds(180, 80, 80, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Close-icon.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 240, 89, 25);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Arrow-Back-icon (1).png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 240, 80, 25);

        tf_busName.setEditable(false);
        getContentPane().add(tf_busName);
        tf_busName.setBounds(180, 120, 81, 30);

        tf_normal.setEditable(false);
        getContentPane().add(tf_normal);
        tf_normal.setBounds(180, 160, 78, 30);

        tf_vip.setEditable(false);
        getContentPane().add(tf_vip);
        tf_vip.setBounds(180, 200, 78, 30);

        jLabel4.setText("VIP Seat :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 210, 60, 16);

        jLabel5.setText("Normal Seat :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 160, 80, 16);

        jLabel6.setText("Bus Name :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 130, 70, 16);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/q0YWfFw.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 380, 320);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        busSelect bs = new busSelect();
        bs.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String busID = (String) cb_busID.getSelectedItem();
        try{
            busTier bt = new busTier();
            boolean success = bt.deleteBus(busID);
            if(!success)
                JOptionPane.showMessageDialog(null, "Fail to Delete bus");
            else{
                JOptionPane.showMessageDialog(null, "Record Delete Successfully");
                dispose();
                busSelect bs = new busSelect();
                bs.setVisible(true);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Fail to retrieve Bus ID");
        } 
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb_busIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_busIDActionPerformed
        try{
            busTier bt = new busTier();
            String busId = (String) cb_busID.getSelectedItem();
            Bus b = new Bus();
            b.setBusID(busId);
            b = bt.retrieveBus(b);
            if(b==null)
            JOptionPane.showMessageDialog(null, "Fail to retrieve Bus record");
            else{
                tf_busName.setText(b.getBusName());
                tf_normal.setText(b.getSeat()+"");
                tf_vip.setText(b.getVip()+"");
            }

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Fail to retrieve Bus details");
        }
    }//GEN-LAST:event_cb_busIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deleteBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deleteBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deleteBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deleteBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deleteBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_busID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tf_busName;
    private javax.swing.JTextField tf_normal;
    private javax.swing.JTextField tf_vip;
    // End of variables declaration//GEN-END:variables
}
