/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import domain.Member;
import domain.Staff;
import javax.swing.JOptionPane;

/**
 *
 * @author han
 */
public class recover extends javax.swing.JFrame {

    /**
     * Creates new form recover
     */
    public recover() {
        initComponents();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        tf_hp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Password Recovery");
        setMinimumSize(new java.awt.Dimension(380, 285));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Password Recovery");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(62, 18, 200, 28);

        jLabel2.setText("Username :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(21, 62, 67, 16);

        jLabel3.setText("Handphone :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(16, 91, 73, 16);
        getContentPane().add(tf_username);
        tf_username.setBounds(100, 59, 156, 30);
        getContentPane().add(tf_hp);
        tf_hp.setBounds(101, 88, 106, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setText("Example:0123456789");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(212, 94, 91, 13);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/User-Administrator-Blue-icon.png"))); // NOI18N
        jButton1.setText("Member");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 130, 107, 33);

        jLabel5.setText("Get Password :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 140, 87, 16);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Groups-Meeting-Light-icon.png"))); // NOI18N
        jButton2.setText("Staff");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 130, 120, 33);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(120, 170, 68, 25);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/q0YWfFw.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 380, 250);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String username = tf_username.getText();
        String hp = tf_hp.getText();
        
        boolean valid = true;
        String invalid = "";
        //Handphone validation
        String handphone=tf_hp.getText();
        if(handphone.length()!=10){
            valid = false;
            invalid = "Handphone number should have 10 number";
        }
        for(int a=0;a<handphone.length();a++){
            char temp1 = handphone.charAt(a);
            if(Character.isLetter(temp1)==true){
                valid = false;
                invalid = "Please insert proper handphone number";
            }
        }
        if(valid){
        try{
            memberTier mt = new memberTier();
            Member m = mt.passRecover(username,hp);
                if(m==null){
                    JOptionPane.showMessageDialog(this, "Incorrect Information, Fail to retrieve password.");
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Username :"+m.getUsername()+"\nPassword :"+m.getPassword());
                    dispose();
                    login l = new login();
                    l.setVisible(true);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        else
            JOptionPane.showMessageDialog(this, invalid);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String username = tf_username.getText();
        String hp = tf_hp.getText();
        
        boolean valid = true;
        String invalid = "";
        //Handphone validation
        String handphone=tf_hp.getText();
        if(handphone.length()!=10){
            valid = false;
            invalid = "Handphone number should have 10 number";
        }
        for(int a=0;a<handphone.length();a++){
            char temp1 = handphone.charAt(a);
            if(Character.isLetter(temp1)==true){
                valid = false;
                invalid = "Please insert proper handphone number";
            }
        }
        if(valid){
        try{
            staffTier st = new staffTier();
            Staff s = st.passRecover(username,hp);
                if(s==null){
                    JOptionPane.showMessageDialog(this, "Incorrect Information, Fail to retrieve password.");
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Username :"+s.getUsername()+"\nPassword :"+s.getPassword());
                    dispose();
                    login l = new login();
                    l.setVisible(true);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        else
            JOptionPane.showMessageDialog(this,invalid);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        login l = new login();
        l.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recover().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tf_hp;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
