/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import domain.Payment;
import domain.Scheduler;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author han
 */
public class refund extends javax.swing.JFrame {

    /**
     * Creates new form refund
     */
    public refund(String memId) {
        initComponents();
        tf_memID.setText(memId);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cb_scheID = new javax.swing.JComboBox<String>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tf_memID = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select Cancellation");
        setMinimumSize(new java.awt.Dimension(755, 425));
        getContentPane().setLayout(null);

        jButton1.setText("Show Available Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(454, 17, 161, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Payment ID", "Schedule ID", "Schedule Date", "Time", "Seat Type", "Seat Booked", "Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(12, 55, 719, 275);

        jLabel2.setText("Select Payment ID : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 344, 117, 28);

        cb_scheID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_scheIDActionPerformed(evt);
            }
        });
        getContentPane().add(cb_scheID);
        cb_scheID.setBounds(141, 347, 90, 22);

        jButton2.setText("Forward to Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(243, 346, 137, 25);

        jButton3.setText("Clear Table");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(622, 17, 109, 25);

        jLabel3.setText("Member ID:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(521, 348, 68, 16);

        tf_memID.setEditable(false);
        getContentPane().add(tf_memID);
        tf_memID.setBounds(594, 345, 72, 22);

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(678, 344, 53, 25);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Select Cancellation");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 13, 151, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/q0YWfFw.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 740, 380);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String memID = tf_memID.getText();
        try{
            payTier pt = new payTier();
            ArrayList<Payment> payarray = pt.retrievePay(memID);
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            DefaultComboBoxModel model2 = (DefaultComboBoxModel)cb_scheID.getModel();
            model.setRowCount(0);
            model2.removeAllElements();

            for(int i=0; i<payarray.size();i++){
                Payment p = payarray.get(i);
                String c1 = p.getPayID();
                String c2 = p.getScheID();
                
                String c3 = p.getScheDate();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                Calendar cal = Calendar.getInstance();
                String today = sdf.format(cal.getTime());
                Date tod = sdf.parse(today);
                Date sched = sdf.parse(c3);
                Date rdate = new Date(sched.getTime()-2*24*3600*1000);

                int t = p.getScheTime();
                String c4 = String.format("%04d",t);
                String c5 = p.getSeatType();
                String c6 = p.getSeatBook()+"";
                String c7 = p.getPrice()+"";
                
                if(tod.equals(rdate)){
                    Object [] row = {c1,c2,c3,c4,c5,c6,c7};
                    model.addRow(row);
                    model2.addElement(c1);
                }else if(tod.before(rdate)){
                    Object [] row = {c1,c2,c3,c4,c5,c6,c7};
                    model.addRow(row);
                    model2.addElement(c1);
                }

            }

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Fail to retrieve record");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb_scheIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_scheIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_scheIDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String payID = (String)cb_scheID.getSelectedItem();
        String memID = tf_memID.getText();
        dispose();
        cancel c = new cancel(payID,memID);
        c.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        DefaultComboBoxModel model2 = (DefaultComboBoxModel)cb_scheID.getModel();
        model2.removeAllElements();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String memId = tf_memID.getText();
        
        dispose();
        showMem sm = new showMem(memId);
        sm.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(refund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(refund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(refund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(refund.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new refund().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_scheID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tf_memID;
    // End of variables declaration//GEN-END:variables
}
