/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import domain.Bus;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author han
 */
public class retrieveBus extends javax.swing.JFrame {

    /**
     * Creates new form retrieveBus
     */
    public retrieveBus() {
        initComponents();
        try{
            busTier bt = new busTier();
            ArrayList busID = bt.getBusList();
            DefaultComboBoxModel model = (DefaultComboBoxModel)cb_busID.getModel();
            for(int i=0; i<busID.size();i++){
                String busId = (String) busID.get(i);
                model.addElement(busId);
            }
                        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Fail to retrieve Bus ID");
        }
        
        this.setLocationRelativeTo(null);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        tf_busName = new javax.swing.JTextField();
        cb_busID = new javax.swing.JComboBox<String>();
        tf_normal = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tf_vip = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Retrieve Bus");
        setFocusTraversalPolicyProvider(true);
        setMinimumSize(new java.awt.Dimension(290, 310));
        getContentPane().setLayout(null);

        jLabel5.setText("Normal Seat :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 130, 80, 16);

        tf_busName.setEditable(false);
        getContentPane().add(tf_busName);
        tf_busName.setBounds(120, 100, 81, 22);

        cb_busID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_busIDActionPerformed(evt);
            }
        });
        getContentPane().add(cb_busID);
        cb_busID.setBounds(120, 72, 90, 20);

        tf_normal.setEditable(false);
        getContentPane().add(tf_normal);
        tf_normal.setBounds(120, 130, 78, 22);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blue-ok-icon (1).png"))); // NOI18N
        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 230, 97, 25);

        jLabel4.setText("VIP Seat :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 160, 58, 16);

        tf_vip.setEditable(false);
        getContentPane().add(tf_vip);
        tf_vip.setBounds(120, 160, 78, 22);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Retrieve Bus");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 20, 131, 28);

        jLabel2.setText("Bus ID :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 80, 45, 16);

        jLabel3.setText("Bus Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 110, 66, 16);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 0, 0);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/q0YWfFw.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 290, 290);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cb_busIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_busIDActionPerformed
        try{
            busTier bt = new busTier();
            String busId = (String) cb_busID.getSelectedItem();
            Bus b = new Bus();
            b.setBusID(busId);
            b = bt.retrieveBus(b);
            if(b==null)
            JOptionPane.showMessageDialog(null, "Fail to retrieve Bus record");
            else{
                tf_busName.setText(b.getBusName());
                tf_normal.setText(b.getSeat()+"");
                tf_vip.setText(b.getVip()+"");
            }

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Fail to retrieve Bus details");
        }
    }//GEN-LAST:event_cb_busIDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        






    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(retrieveBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(retrieveBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(retrieveBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(retrieveBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new retrieveBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_busID;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tf_busName;
    private javax.swing.JTextField tf_normal;
    private javax.swing.JTextField tf_vip;
    // End of variables declaration//GEN-END:variables
}
