/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import domain.Staff;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author han
 */
public class retrieveStaff extends javax.swing.JFrame {

    /**
     * Creates new form retrieveStaff
     */
    public retrieveStaff() {
        initComponents();
        try{
            staffTier st = new staffTier();
            ArrayList staffID = st.getStaffList();
            DefaultComboBoxModel model = (DefaultComboBoxModel)cb_staffID.getModel();
            for(int i=0; i<staffID.size();i++){
                String staffId = (String) staffID.get(i);
                model.addElement(staffId);
            }
                        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Fail to retrieve Staff ID");
        }
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_birth = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf_address = new javax.swing.JTextArea();
        cb_staffID = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        tf_password = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_hp = new javax.swing.JTextField();
        tf_name = new javax.swing.JTextField();
        tf_username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_salary = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Retrieve Staff");
        setMinimumSize(new java.awt.Dimension(470, 530));
        getContentPane().setLayout(null);

        tf_birth.setEditable(false);
        getContentPane().add(tf_birth);
        tf_birth.setBounds(110, 162, 199, 30);

        jLabel4.setText("Staff ID :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 50, 52, 16);

        tf_address.setEditable(false);
        tf_address.setColumns(20);
        tf_address.setRows(5);
        jScrollPane1.setViewportView(tf_address);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 240, 166, 96);

        cb_staffID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_staffIDActionPerformed(evt);
            }
        });
        getContentPane().add(cb_staffID);
        cb_staffID.setBounds(110, 50, 120, 30);

        jLabel8.setText("Username :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 340, 67, 16);

        jLabel3.setText("Brithday :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 170, 55, 16);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blue-ok-icon (1).png"))); // NOI18N
        jButton3.setText("Confirm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(140, 440, 110, 25);

        tf_password.setEditable(false);
        getContentPane().add(tf_password);
        tf_password.setBounds(110, 380, 211, 22);

        jLabel6.setText("Salary : RM");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 210, 67, 16);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Retrieve Staff");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 10, 140, 28);

        jLabel2.setText("Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(41, 93, 42, 16);

        jLabel9.setText("Password :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 380, 64, 16);

        tf_hp.setEditable(false);
        getContentPane().add(tf_hp);
        tf_hp.setBounds(110, 122, 120, 30);

        tf_name.setEditable(false);
        tf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nameActionPerformed(evt);
            }
        });
        getContentPane().add(tf_name);
        tf_name.setBounds(110, 82, 168, 30);

        tf_username.setEditable(false);
        tf_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(tf_username);
        tf_username.setBounds(110, 342, 209, 30);

        jLabel7.setText("Handphone :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 130, 73, 16);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setText("Example : 016228776");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(250, 130, 92, 20);

        jLabel5.setText("Address :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 240, 55, 16);

        tf_salary.setEditable(false);
        tf_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_salaryActionPerformed(evt);
            }
        });
        getContentPane().add(tf_salary);
        tf_salary.setBounds(110, 202, 80, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/q0YWfFw.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(-40, 0, 540, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cb_staffIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_staffIDActionPerformed
        try{
            staffTier st = new staffTier();
            String staffId = (String) cb_staffID.getSelectedItem();
            Staff s = new Staff();
            s.setStaffID(staffId);
            s = st.retrieveStaff(s);
            if(s==null)
            JOptionPane.showMessageDialog(null, "Fail to retrieve Staff record");
            else{
                tf_name.setText(s.getStaffName());
                tf_hp.setText(s.getHp());
                tf_birth.setText(s.getBirth());
                tf_salary.setText(s.getSalary()+"");
                tf_address.setText(s.getAddress());
                tf_username.setText(s.getUsername());
                tf_password.setText(s.getPassword());

            }

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Fail to retrieve Bus details");
        }
    }//GEN-LAST:event_cb_staffIDActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        staffSelect ss= new staffSelect();
        ss.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tf_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nameActionPerformed

    private void tf_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_salaryActionPerformed

    private void tf_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(retrieveStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(retrieveStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(retrieveStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(retrieveStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new retrieveStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_staffID;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tf_address;
    private javax.swing.JTextField tf_birth;
    private javax.swing.JTextField tf_hp;
    private javax.swing.JTextField tf_name;
    private javax.swing.JPasswordField tf_password;
    private javax.swing.JTextField tf_salary;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
