/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import domain.Scheduler;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author han
 */
public class scheChoice extends javax.swing.JFrame {

    /**
     * Creates new form scheChoice
     */
    public scheChoice() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cb_scheID = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Schedule Selection");
        setMinimumSize(new java.awt.Dimension(761, 435));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Manage Schedule");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 13, 181, 28);

        jButton1.setText("Add new Schedule");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(337, 18, 139, 25);

        jButton2.setText("Cancel Schedule");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(408, 349, 144, 25);

        jButton3.setText("Update Schedule");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(257, 349, 144, 25);

        jButton4.setText("Show Scheduler");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(488, 18, 125, 25);

        jButton5.setText("Clear Table");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(620, 18, 109, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Scheduler ID", "Destination", "Departure Date", "Time", "Bus ID", "Driver ID"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(12, 61, 705, 275);

        cb_scheID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_scheIDActionPerformed(evt);
            }
        });
        getContentPane().add(cb_scheID);
        cb_scheID.setBounds(149, 352, 90, 22);

        jLabel3.setText("Select Scheduler ID : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(12, 349, 125, 28);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Arrow-Back-icon (1).png"))); // NOI18N
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(624, 349, 93, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/q0YWfFw.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 740, 390);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try{
            scheTier st = new scheTier();
            ArrayList<Scheduler> schearray = st.retrieveSche();
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            DefaultComboBoxModel model2 = (DefaultComboBoxModel)cb_scheID.getModel();
            model.setRowCount(0);
            model2.removeAllElements();

            for(int i=0; i<schearray.size();i++){
                Scheduler s = schearray.get(i);
                String c1 = s.getScheID();
                String c2 = s.getDest();
                String c3 = s.getScheDate();
                int t = Integer.parseInt(s.getDeparture());
                String c4 = String.format("%04d",t);
                String c5 = s.getBusID();
                String c6 = s.getDriverID();
                String c7 = s.getNormal();
                String c8 = s.getVip();

                Object [] row = {c1,c2,c3,c4,c5,c6,c7,c8};
                model.addRow(row);
                model2.addElement(c1);
                
            }

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Fail to retrieve record");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        DefaultComboBoxModel model2 = (DefaultComboBoxModel)cb_scheID.getModel();
        model2.removeAllElements();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cb_scheIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_scheIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_scheIDActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        dispose();
        showStaff ss = new showStaff();
        ss.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            scheTier st = new scheTier();
            String newID = st.getNewID();
                if (newID == null){
                    JOptionPane.showMessageDialog(this, "Fail to get new Schedule id");
                } else {
                    dispose();
                    createSche cs = new createSche(newID);
                    cs.setVisible(true);
                }
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String scheID = (String)cb_scheID.getSelectedItem();
        try{
            scheTier st = new scheTier();
            boolean success = st.deleteSche(scheID);
            if(!success)
                JOptionPane.showMessageDialog(null, "Fail to delete record");
            else{
                JOptionPane.showMessageDialog(null, "Schedule had been deleted.");
                dispose();
                scheChoice sc = new scheChoice();
                sc.setVisible(true);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Fail to delete record");
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        String scheID = (String)cb_scheID.getSelectedItem();
        updateSche us = new updateSche(scheID);
        us.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scheChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scheChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scheChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scheChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scheChoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_scheID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
