/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import domain.Member;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author han
 */
public class showMem extends javax.swing.JFrame {

    /**
     * Creates new form showMem
     */
    public showMem(String MemId) {
        initComponents();
       // getContentPane().setBackground(Color.WHITE);
        tf_memID.setText(MemId);
        String MemID = tf_memID.getText();
        try{
            memberTier mt = new memberTier();
            Member m = new Member();
            m = mt.retrieveMem(MemID);
                if (m == null){
                    JOptionPane.showMessageDialog(this, "Failed to retrieve Member data.");
                } else {
                    tf_name.setText(m.getMemName());
                    tf_hp.setText(m.getHp());
                    tf_address.setText(m.getAddress());
                    tf_gender.setText(m.getGender());
                    tf_birth.setText(m.getBirth());
                    tf_username.setText(m.getUsername());
                }
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_memID = new javax.swing.JTextField();
        tf_name = new javax.swing.JTextField();
        tf_username = new javax.swing.JTextField();
        tf_gender = new javax.swing.JTextField();
        tf_hp = new javax.swing.JTextField();
        tf_birth = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf_address = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Member Details");
        setMinimumSize(new java.awt.Dimension(492, 516));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Member Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 18, 165, 28);

        jLabel2.setText("Member ID :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 62, 72, 16);

        jLabel3.setText("Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(42, 91, 42, 16);

        jLabel4.setText("Gender :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(25, 126, 50, 16);

        jLabel5.setText("Handphone :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(6, 155, 73, 16);

        jLabel6.setText("Address :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 245, 55, 16);

        jLabel7.setText("Birthday :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 219, 55, 16);

        jLabel8.setText("Username :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(12, 190, 67, 16);

        tf_memID.setEditable(false);
        getContentPane().add(tf_memID);
        tf_memID.setBounds(96, 59, 67, 22);

        tf_name.setEditable(false);
        getContentPane().add(tf_name);
        tf_name.setBounds(96, 88, 132, 30);

        tf_username.setEditable(false);
        getContentPane().add(tf_username);
        tf_username.setBounds(91, 187, 134, 22);

        tf_gender.setEditable(false);
        getContentPane().add(tf_gender);
        tf_gender.setBounds(87, 123, 70, 30);

        tf_hp.setEditable(false);
        getContentPane().add(tf_hp);
        tf_hp.setBounds(90, 160, 111, 22);

        tf_birth.setEditable(false);
        getContentPane().add(tf_birth);
        tf_birth.setBounds(87, 216, 118, 22);

        tf_address.setEditable(false);
        tf_address.setColumns(20);
        tf_address.setRows(5);
        jScrollPane1.setViewportView(tf_address);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(87, 245, 190, 120);

        jLabel9.setText("Forward To :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 410, 76, 16);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Household-Booking-icon.png"))); // NOI18N
        jButton1.setText("Booking");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 410, 97, 25);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Close-icon.png"))); // NOI18N
        jButton2.setText("Cancellation");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 410, 121, 25);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit-validated-icon.png"))); // NOI18N
        jButton3.setText("Update Personnel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(100, 370, 161, 33);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Arrow-Back-icon (1).png"))); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(350, 410, 90, 25);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/q0YWfFw.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 480, 510);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String memId = tf_memID.getText();
        dispose();
        showSche ss = new showSche(memId);
        ss.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String memID = tf_memID.getText();
        String name = tf_name.getText();
        String gender = tf_gender.getText();
        String hp = tf_hp.getText();
        String username = tf_username.getText();
        String birth = tf_birth.getText();
        String address = tf_address.getText();
        
        dispose();
        updateMem um = new updateMem(memID,name,gender,hp,username,birth,address);
        um.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String memId = tf_memID.getText();
        
        dispose();
        refund r = new refund(memId);
        r.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(this,"Returning to login page?");
        if(x== 0){
        dispose();
        login l = new login();
        l.setVisible(true);
        }if(x==1){
        
        JOptionPane.showMessageDialog(this,"Stay Back Confirmed");
        }     
        
    
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new showMem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tf_address;
    private javax.swing.JTextField tf_birth;
    private javax.swing.JTextField tf_gender;
    private javax.swing.JTextField tf_hp;
    private javax.swing.JTextField tf_memID;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
