/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import domain.Bus;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author han
 */
public class updateBus extends javax.swing.JFrame {

    /**
     * Creates new form updateBus
     */
    public updateBus() {
        initComponents();
        try{
            busTier bt = new busTier();
            ArrayList busID = bt.getBusList();
            DefaultComboBoxModel model = (DefaultComboBoxModel)cb_busID.getModel();
            for(int i=0; i<busID.size();i++){
                String busId = (String) busID.get(i);
                model.addElement(busId);
            }
                        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Fail to retrieve Bus ID");
        }
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_normal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tf_vip = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_busName = new javax.swing.JTextField();
        cb_busID = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Bus");
        setMinimumSize(new java.awt.Dimension(375, 323));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Update Bus");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 60, 118, 28);
        getContentPane().add(tf_normal);
        tf_normal.setBounds(170, 152, 80, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blue-ok-icon (1).png"))); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 230, 100, 25);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Arrow-Back-icon (1).png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 230, 90, 25);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("VIP Seat :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(88, 190, 80, 16);
        getContentPane().add(tf_vip);
        tf_vip.setBounds(170, 182, 80, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Bus ID :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(95, 110, 70, 16);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Bus Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(76, 140, 90, 16);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Normal Seat :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 170, 110, 16);
        getContentPane().add(tf_busName);
        tf_busName.setBounds(170, 122, 90, 30);

        cb_busID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_busIDActionPerformed(evt);
            }
        });
        getContentPane().add(cb_busID);
        cb_busID.setBounds(170, 100, 100, 22);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/q0YWfFw.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 390, 330);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String busID = (String) cb_busID.getSelectedItem();
        String busName = tf_busName.getText();
        String  seat = tf_normal.getText();
        String vipp =tf_vip.getText();
        
        boolean valid = true;
        String invalid = "";
        
        for(int a=0;a<seat.length();a++){
            char temp1 = seat.charAt(a);
            if(Character.isLetter(temp1)==true){
                valid = false;
                invalid = "Please insert only number for Seat Number";
            }
        }
        
        for(int i=0;i<vipp.length();i++){
            char temp = vipp.charAt(i);
            if(Character.isLetter(temp)==true){
                valid = false;
                invalid = "Please insert only number for Seat Number";
            }
        }
        
        if(valid){   
        try{
        int seatt = Integer.parseInt(seat);
        int vip=Integer.parseInt(vipp);
            busTier bt = new busTier();
            boolean success =bt.updateBus(busID,busName, seatt,vip);
            if(success){
                JOptionPane.showMessageDialog(this,"Update Success");
            }else
            JOptionPane.showMessageDialog(this,"Error");

        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        }
        else
            JOptionPane.showMessageDialog(this,invalid);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        busSelect bs = new busSelect();
        bs.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cb_busIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_busIDActionPerformed
        try{
            busTier bt = new busTier();
            String busId = (String) cb_busID.getSelectedItem();
            Bus b = new Bus();
            b.setBusID(busId);
            b = bt.retrieveBus(b);
            if(b==null)
                JOptionPane.showMessageDialog(null, "Fail to retrieve Bus record");
            else{
                tf_busName.setText(b.getBusName());
                tf_normal.setText(b.getSeat()+"");
                tf_vip.setText(b.getVip()+"");
            }
                        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Fail to retrieve Bus details");
        }
    }//GEN-LAST:event_cb_busIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_busID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tf_busName;
    private javax.swing.JTextField tf_normal;
    private javax.swing.JTextField tf_vip;
    // End of variables declaration//GEN-END:variables
}
