/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import domain.Staff;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author han
 */
public class updateStaff extends javax.swing.JFrame {

    /**
     * Creates new form updateStaff
     */
    public updateStaff() {
        initComponents();
        try{
            staffTier st = new staffTier();
            ArrayList staffID = st.getStaffList();
            DefaultComboBoxModel model = (DefaultComboBoxModel)cb_staffID.getModel();
            for(int i=0; i<staffID.size();i++){
                String staffId = (String) staffID.get(i);
                model.addElement(staffId);
            }
                        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Fail to retrieve Staff ID");
        }
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tf_hp = new javax.swing.JTextField();
        tf_name = new javax.swing.JTextField();
        tf_username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_birth = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf_address = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tf_password = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_salary = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb_staffID = new javax.swing.JComboBox<String>();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Staff");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(350, 485));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Update Staff");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(93, 13, 127, 28);

        jLabel2.setText("Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 90, 42, 16);

        jLabel9.setText("Password :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 340, 64, 16);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/blue-ok-icon (1).png"))); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 400, 100, 25);
        getContentPane().add(tf_hp);
        tf_hp.setBounds(100, 112, 112, 30);

        tf_name.setEditable(false);
        tf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nameActionPerformed(evt);
            }
        });
        getContentPane().add(tf_name);
        tf_name.setBounds(100, 82, 168, 30);
        getContentPane().add(tf_username);
        tf_username.setBounds(100, 310, 209, 30);

        jLabel7.setText("Handphone :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 120, 73, 16);

        jLabel5.setText("Address :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 210, 55, 16);

        tf_birth.setEditable(false);
        getContentPane().add(tf_birth);
        tf_birth.setBounds(100, 142, 199, 30);

        tf_address.setColumns(20);
        tf_address.setRows(5);
        jScrollPane1.setViewportView(tf_address);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 210, 166, 96);

        jLabel8.setText("Username :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 310, 67, 16);

        jLabel3.setText("Brithday :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 150, 55, 16);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Close-icon.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 400, 90, 25);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Arrow-Back-icon (1).png"))); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(230, 400, 90, 25);
        getContentPane().add(tf_password);
        tf_password.setBounds(100, 340, 210, 30);

        jLabel6.setText("Salary : RM");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 180, 67, 16);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setText("Example : 016228776");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(214, 125, 92, 13);

        tf_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_salaryActionPerformed(evt);
            }
        });
        getContentPane().add(tf_salary);
        tf_salary.setBounds(100, 172, 63, 30);

        jLabel4.setText("Staff ID :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 60, 52, 16);

        cb_staffID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_staffIDActionPerformed(evt);
            }
        });
        getContentPane().add(cb_staffID);
        cb_staffID.setBounds(100, 60, 90, 22);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/q0YWfFw.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(-10, 0, 340, 460);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String staffID = (String) cb_staffID.getSelectedItem();
        String name=tf_name.getText();
        String birth=tf_birth.getText();
        String handphone=tf_hp.getText();
        String address=tf_address.getText();
        String salaryy=tf_salary.getText();
        double salary = Double.parseDouble(salaryy);
        String username=tf_username.getText();
        String password =tf_password.getText();
        
        boolean valid = true;
        String invalid = "";
        
        //Salary validation
        for(int i=0;i<salaryy.length();i++){
            char temp = salaryy.charAt(i);
            if(Character.isLetter(temp)==true){
                valid = false;
                invalid = "Please insert number only for salary";
            }
        }        
        
        //Handphone validation
        if(handphone.length()!=10){
            valid = false;
            invalid = "Handphone number should have 10 number";
        }
        for(int a=0;a<handphone.length();a++){
            char temp1 = handphone.charAt(a);
            if(Character.isLetter(temp1)==true){
                valid = false;
                invalid = "Please insert proper handphone number";
            }
        }
        
        if(valid){
        try{
            Staff s = new Staff();
            s.setAddress(address);
            s.setBirth(birth);
            s.setHp(handphone);
            s.setPassword(password);
            s.setSalary(salary);
            s.setStaffID(staffID);
            s.setStaffName(name);
            s.setUsername(username);
            
            
            staffTier st = new staffTier();
            boolean success=st.updateStaff(s);
            if (!success){
                JOptionPane.showMessageDialog(this, "Error updating staff");
            } else {
                JOptionPane.showMessageDialog(this, "Update success.");
                dispose();
                staffSelect ss = new staffSelect();
                ss.setVisible(true);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        }else
            JOptionPane.showMessageDialog(this,invalid);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        tf_hp.setText("");
        tf_address.setText("");
        tf_salary.setText("");
        tf_username.setText("");
        tf_password.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        staffSelect ss= new staffSelect();
        ss.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tf_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_salaryActionPerformed

    private void cb_staffIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_staffIDActionPerformed
        try{
            staffTier st = new staffTier();
            String staffId = (String) cb_staffID.getSelectedItem();
            Staff s = new Staff();
            s.setStaffID(staffId);
            s = st.retrieveStaff(s);
            if(s==null)
                JOptionPane.showMessageDialog(null, "Fail to retrieve Staff record");
            else{
                tf_name.setText(s.getStaffName());
                tf_hp.setText(String.format("%04d",s.getHp()));
                tf_birth.setText(s.getBirth());
                tf_salary.setText(s.getSalary()+"");
                tf_address.setText(s.getAddress());
                tf_username.setText(s.getUsername());
                tf_password.setText(s.getPassword());
                
            }
                        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Fail to retrieve Bus details");
        }
    }//GEN-LAST:event_cb_staffIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_staffID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tf_address;
    private javax.swing.JTextField tf_birth;
    private javax.swing.JTextField tf_hp;
    private javax.swing.JTextField tf_name;
    private javax.swing.JPasswordField tf_password;
    private javax.swing.JTextField tf_salary;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
